### ISSUE TITLE
Blinkt won't light

### ISSUE THREAD

**Issue by kuehnd96** [jimbobbennett/BusyLight#6]
Hello. Thank you for creating this repo and for the time it took to set up. I completed the step to get the code installed on my Raspberry Pi 3B but my Blinkt is not lighting up when I send it an update color command. I will attach some screen shots to this issue of my Azure setup. The task manager in Raspberry Pi OS shows the BusyLight/app.py running. Outside of a bad piece of Blinkt hardware can you think of any reason why this won't light? Any help is appreciated. Thank you.

**Comment by kuehnd96** [comment]
Azure IoT hub shows connection to the device.

![BusyLightConnectionStatus](https://user-images.githubusercontent.com/10777071/160313862-2ffd7d76-200d-44b1-86b0-55cd562300f9.png)

**Comment by kuehnd96** [comment]
It appears that commands are getting to and coming back from the Pi.

![BusyLightCommandList](https://user-images.githubusercontent.com/10777071/160313921-dcf83865-615f-41f8-8441-4992d73fdb78.png)

**Comment by kuehnd96** [comment]
This is what I get when I open the pending commands link. Pending commands suggest a problem to me but I have never used this Azure offering before.

![BusyLightPendingCommands](https://user-images.githubusercontent.com/10777071/160313992-33988f70-9108-462d-a892-8f90cc895d67.png)

**Comment by kuehnd96** [comment]
I am going to dive into my first python experience and see if I can find some code and/or instructions to try and simply light this Blinkt.

**Comment by kuehnd96** [comment]
My hardware appears to be the problem. I ran the instructions to light the LED's on the Blinkt from the manufacturer and nothing worked. Please close this issue. Thanks.

**Comment by jimbobbennett** [comment]
OK, will close. Thank you for raising this and investigating!
